version: '3.7'
services:
  ignite-server-node-1:
    image: apacheignite/ignite:2.8.1
    container_name: ignite-server-node-1
    environment:
      - CONFIG_URI=/opt/ignite/ext-config/ignite-config-node1.xml
      - OPTION_LIBS=ignite-rest-http
      - IGNITE_WORK_DIR=/opt/ignite/work
    ports:
      - "47500:47500"
      - "47100:47100"
    networks:
      - ignite-net
    volumes:
      - ../config:/opt/ignite/ext-config
      - ../work:/opt/ignite/work
      - ../libs/control-center-agent/bin/management.sh:/opt/ignite/apache-ignite/bin/management.sh
      - ../libs/control-center-agent/libs/control-center-agent:/opt/ignite/apache-ignite/libs/control-center-agent

# ------ Ucomment the settings below to create a two-node cluster -----
#
#  ignite-server-node-2:
#    image: apacheignite/ignite:2.8.1
#    container_name: ignite-server-node-2
#    environment:
#      - CONFIG_URI=/opt/ignite/ext-config/ignite-config-node2.xml
#      - OPTION_LIBS=ignite-rest-http
#      - IGNITE_WORK_DIR=/opt/ignite/work
#    ports:
#      - "47501:47501"
#      - "47101:47101"
#    networks:
#      - ignite-net
#    volumes:
#      - ../config:/opt/ignite/ext-config
#      - ../work:/opt/ignite/work
#      - ../libs/control-center-agent/bin/management.sh:/opt/ignite/apache-ignite/bin/management.sh
#      - ../libs/control-center-agent/libs/control-center-agent:/opt/ignite/apache-ignite/libs/control-center-agent

networks:
  ignite-net:
    driver: bridge
